#%RAML 1.0
title: Liftago Public API
version: v1

baseUri: https://api.liftago.com/v1/partners/{partnerId}
annotationTypes:
  javaName:
    allowedTargets: [TypeDeclaration, Method]

description: |
  Delivery API for external integration.

/deliveryRides:
  post:
    description: Creates a new delivery ride
    body:
      application/json:
        type: CreateDeliveryRideRequest
    responses:
      201:
        body:
          application/json:
            type: DeliveryRideInfo
        headers:
          Location:
            description: URI of created delivery ride
            example: /deliveryRides/30dd67cc-b596-11e8-96f8-529269fb1459
      400:
        body:
          application/json:
            type: MalformedInputError
      404:
        body:
          application/json:
            type: PartnerNotFoundError
      409:
        body:
          application/json:
            type: DuplicatedRideIdError


  /{rideId}:
    uriParameters:
          rideId:
            type: string
    get:
      description: Gets info about the delivery ride
      responses:
        200:
          body:
            application/json:
              type: DeliveryRideInfo

        404:
          body:
            application/json:
              type: RideNotFoundError
    /cancel:
      post:
        description: Cancels ride
        body:
          application/json:
            type: CancelRequest
        responses:
          204:
          400:
            body:
              application/json:
                type: MalformedInputError
          404:
            body:
              application/json:
               type: RideNotFoundError
          409:
            body:
              application/json:
               type: IncompatibleStateError

    /stops:
      /{stopId}:
        uriParameters:
          stopId: string
        /update:
          post:
            description: Updates the stop
            body:
              application/json:
                type: UpdateStopRequest
            responses:
              204:
              400:
                body:
                  application/json:
                    type: MalformedInputError
              403:
                body:
                  application/json:
                    type: UpdateNotAllowedError
              404:
                body:
                  application/json:
                    type: StopNotFoundError
              409:
                body:
                  application/json:
                   type: IncompatibleStateError

  /availability:
    post:
      description: Returns expected availability of Liftago drivers at a specified time and place.
      body:
        application/json:
          type: DriverAvailabilityRequest
      responses:
        200:
          body:
            application/json:
              type: DriverAvailability
        400:
          body:
            application/json:
              type: MalformedInputError


types:
  DeliveryRide:
    type: object
    properties:
      id:
        type: string
        description: |
          Unique ID provided by the partner which will be used in reports
          and to detect duplicate POSTs
        pattern: "[a-zA-Z0-9-_]+"
        maxLength: 40

  Stop:
    type: object
    properties:
      stopId:
        type: string
        description: Provided by the partner. Unique within the ride.
      location: Location
      contact:
        type: Person
        description: Contact person assuming the role of a sender (for "pickup") or a recipient (for "destination" or "fallback destination").
      noteForDriver:
        type: string
        description: Localized message for the driver.
      kind:
        type: string
        description: PICKUP | DESTINATION | FALLBACK_DESTINATION
      verificationCode:
        type: string
        minLength: 4
        maxLength: 10
        required: false
        description: Code (PIN, Password) to be used to proof the identity of a recepient. Always has to be null for PICKUP stops.

  CreateDeliveryRideRequest:
    type: DeliveryRide
    properties:
      productSettingId?:
        type: string
        description: |
            identifies various delivery ride settings, such as prize per leg, proof of identity requirements, etc.
            ProductSettings are managed by the account operator.
      stops:
        type: Stop[]
        description: must start an element with the kind "pickup", followed by 1+ elements with the kind "destination" and followed by 0+ "fallback_destinations".
      webHook?:
        type: object
        description: |
          If present, Liftago will send POST request to this URI, with given
          headers and body containing StatusChangedEvent on every relevant
          ride change.
        properties:
          url:
            type: URI
            description: URI to be called
          headers:
            type: Header[]
            maxItems: 10
      webHookV2?:
        type: object
        description: |
            If present, Liftago will send POST request only to this `url`, with given
            `headers` and body containing `WebHookPayload` on every relevant ride or stop change.
            `WebHookPayload` is of type

            ```
              WebHookPayload:
                type: object
                properties:
                  action: WebHookAction
                  eventId: string
                  rideId: string
                  stopId?: string
                  links: RideLink
            ```
            where `WebHookAction` is one of
            `STOP_DELIVERED`, `STOP_UNDELIVERED`, `RIDE_PROCESSING`, `RIDE_ACCEPTED`, `RIDE_WAITING`, `RIDE_ON_BOARD`, `RIDE_COMPLETED`, `RIDE_CANCELLED` or `RIDE_REJECTED`.

            and `RideLink` is of type

            ```
              RideLink:
                type: object
                properties:
                  ride:
                    type: string
                    description: URI of the ride
            ```
        properties:
          url:
            type: URI
            description: URI to be called
          headers:
            type: Header[]
            maxItems: 10

  DeliveryRideInfo:
    type: DeliveryRide
    properties:
      rideStatus: RideStatus
      deliveryStatus:
          type: object
          properties:
            nextStop?:
              type: string
              description: StopId
      cancelledBy?:
        enum:
          - DRIVER
          - SENDER
      driver?:
        type: Driver
        description: Will be present once the ride is ACCEPTED
      car?:
        type: Car
        description: Will be present once the ride is ACCEPTED
      taxiPosition?:
        type: Coordinates
        description: |
          Last known taxi position.
          Will be available when the DRV starts comming for the package (can be null even if the ride is ACCEPTED).
          Position can be also tracked via Ridesharing location url in the links.
      price:
        type: Money
        description: Total fixed price - available immediatelly - will change if the driver has to travel back to the sender or the fallback depot.
      pickupArrivalEstimateAt?:
        type: datetime
        description: |
          Estimate of the taxi arrival to the pickup point.
          Not updated in case of delay.
          Updated in case of a driver cancellation.
          (available when the ride is ACCEPTED)
      destinationArrivalEstimateAt?:
        type: datetime
        description: |
          Estimate of the taxi arrival to the destination point.
          Not updated in case of delay.
          Updated in case of a driver cancellation. (NULL while we're looking for a new driver and new ETA once we find him)
          Updated if the driver has to travel back to the sender or the fallback depot.
          (available when the ride is ACCEPTED)
      completedAt?:
        type: datetime
        description: When was the ride finished/cancelled
      stops:
        type: StopInfo[]
      links:
        type: object
        properties:
          self: URI
          position?: URI
          cancel: URI

  StopInfo:
    type: object
    properties:
      id: string
      lastDeliveryAttempt?: datetime
      state: StopState
      kind:
        type: string
        description: PICKUP | DESTINATION | FALLBACK_DESTINATION

  RideStatus:
    enum:
      - PROCESSING
      - ACCEPTED
      - WAITING
      - ON_BOARD
      - COMPLETED
      - CANCELLED
      - REJECTED
    description: |
      - PROCESSING - ride is being processed, driver not found yet. Transitions to ACCEPTED, REJECTED or CANCELLED BY SENDER
      - ACCEPTED - driver found and selected. Transitions to WAITING or CANCELLED (either by DRIVER OR SENDER)
      - WAITING - driver is waiting on pickup location. Transitions to ON_BOARD or CANCELLED (either by DRIVER or SENDER)
      - ON_BOARD - passenger on board. Transitions to COMPLETED
      - COMPLETED - ride finished
      - CANCELLED - ride cancelled
      - REJECTED - could not find taxi in time

  StopState:
    enum:
      - IN_QUEUE
      - DELIVERED
      - UNDELIVERED
    description: |
      - IN_QUEUE - no delivery attempt yet
      - DELIVERED - delivered attempt succeeded
      - UNDELIVERED - last delivery attempt failed

  WebHookAction:
    enum:
      - STOP_IN_QUEUE
      - STOP_DELIVERED
      - STOP_UNDELIVERED
      - RIDE_PROCESSING
      - RIDE_ACCEPTED
      - RIDE_WAITING
      - RIDE_ON_BOARD
      - RIDE_COMPLETED
      - RIDE_CANCELLED
      - RIDE_REJECTED
    description: Actions correspond to changes in possible ride or stop states

  URI: string

  RideLink:
    type: object
    properties:
      ride:
        type: URI
        description: URI of the ride

  Header:
    type: object
    properties:
      name: string
      value: string

  Money:
    type: object
    properties:
      amount: number
      ccy: Currency

  Currency:
    type: string
    description: ISO-4217 (EUR, CZK)

  Coordinates:
    type: object
    properties:
      lat?:
        type: number
        format: double
      lon?:
        type: number
        format: double

  Address:
    type: object
    properties:
      street: string
      houseNumber: string
      city: string
      zipCode: string
      country: string
      description?: string

  Location:
    type: object
    properties:
      coordinates?: Coordinates
      address?: Address

  Person:
    type: object
    properties:
      name: string
      email?: string
      company?: string
      phoneNumber:
        type: string
        description:  Phone number with international prefix

  Driver:
    type: object
    properties:
      name: string
      phoneNumber?:
        type: string
        description: Phone number to driver (goes through exchange)
      image?: URI

  Car:
    type: object
    properties:
      color:
        enum: [BLACK, BLUE, BROWN, GREEN, ORANGE, PURPLE, RED, SILVER, WHITE, YELLOW]
      brand: string
      model: string
      licencePlate: string

  WebHookEvent:
    type: object
    properties:
      eventId:
        type: string
        description: Unique event identifier
      eventType:
        enum:
          - status_changed
        description:
          status_changed - Ride and/or delivery status changed
          Clients have to ignore unknown eventTypes
      timestamp:
        type: datetime
        description: When the event occured.

  StatusChangedEvent:
    type: WebHookEvent
    properties:
      rideId: string
      rideStatus: string
      nextStopId?: string
      links:
        type: object
        properties:
          ride:
            type: URI
            description: URI of the ride

  WebHookPayload:
    type: object
    properties:
      action: WebHookAction
      eventId: string
      rideId: string
      stopId?: string
      links: RideLink

  CancelRequest:
    type: object
    properties:
      reason?: string
      comment?:
        type: string
        description: Text comment about cancallation reason

  UpdateStopRequest:
    type: object
    properties:
      update:
        type: string
        description: POSTPONE_TO_END | CANCEL

  DriverAvailabilityRequest:
    type: object
    properties:
      pickup: Location
      destination?: Location
      expectedTimeOfTakeOver: datetime

  DriverAvailability:
    type: DriverAvailabilityRequest
    properties:
      guaranteed:
        type: boolean
        description: True if Liftago confirms that it will provide a driver for a delivery requested at the specified time and place.

  Error:
    type: object
    properties:
      code: string
      message: string

  MalformedInputError:
    type: Error
    example: {"code": "malformed_json_request", "message": "Malformed json request"}

  RideNotFoundError:
    type: Error
    example: {"code":"ride_not_found", "message":"Ride '52b4f17d-cb60-41a5-a1c5-f901167e5bdc' does not exist"}

  StopNotFoundError:
    type: Error
    example: {"code":"stop_not_found", "message":"Stop '33d6953e-f533-4d1b-bb69-3092e0b51f23' does not exist for ride 'f9852152-1754-438e-a5ab-9a614339875a'"}

  UpdateNotAllowedError:
    type: Error
    example: {"code": "update_not_allowed", "message": "Updates not allowed"}

  PartnerNotFoundError:
    type: Error
    example: {"code":"partner_not_found", "message":"Partner 'UNKNOWN' does not exist"}

  DuplicatedRideIdError:
    type: Error
    example: {"code":"current_ride_exists", "message":"Ride '52b4f17d-cb60-41a5-a1c5-f901167e5bdc' already exists"}

  IncompatibleStateError:
    type: Error
    example: {"code":"incompatible_state", "message":"Ride '52b4f17d-cb60-41a5-a1c5-f901167e5bdc' is not in the state compatible with the requested action"}

  UnsupportedLocationError:
    type: Error
    example: {"code":"unsupported_location", "message":"Requested route is located in an unsupported area."}

  UnsupportedUpdateError:
    type: Error
    example: {"code":"unsupported_update", "message":"Stop is of kind 'PICKUP', must be 'DESTINATION'"}

  UnrecognizedLocationError:
    type: Error
    example: {"code":"unrecognized_location", "message":"Requested route contains an unrecognizable address."}

  NotEnoughStopsError:
    type: Error
    example: {"code":"not_enough_stops", "message":"Required at least 2 stops, got 1."}
